"""Render a DEMO_GUIDE.md from a HostileGenerationResult.

Keeps the guide and the generator's case list in sync by deriving the
document directly from `HostileCase` entries instead of hand-maintaining a
parallel description.
"""

from __future__ import annotations

from pathlib import Path

from src.hostile_demo_generator import HostileGenerationResult

_DOMAIN_TITLES = {
    "sociodemo": "Sociodemographics",
    "biometrics": "Biometrics",
    "environment_mri": "Environment / MRI",
    "subject_session": "Subject / Session IDs + DataLad",
    "entity_rewrite": "BIDS Entity Rewriting (task/acq/run)",
    "recipes": "Recipe Definitions (survey + biometrics scoring)",
    "input_formats": "Input Format Diversity (encodings, spreadsheets)",
    "survey_full_run": "Full Survey Run (random template + import + scoring)",
}


def render_demo_guide(result: HostileGenerationResult) -> str:
    lines: list[str] = [
        "# PRISM Hostile Demo",
        "",
        "This project was generated by `prism_tools dataset build-hostile-demo` "
        "to deliberately exercise edge cases across sociodemographics, "
        "biometrics, environmental/MRI data, and subject/session identifiers. "
        "Each case below names the injected hostile value and the expected "
        "pipeline behavior.",
        "",
    ]

    by_domain: dict[str, list] = {}
    for case in result.cases:
        by_domain.setdefault(case.domain, []).append(case)

    for domain, title in _DOMAIN_TITLES.items():
        cases = by_domain.get(domain, [])
        if not cases:
            continue
        lines.append(f"## {title}")
        lines.append("")
        lines.append("| Case ID | Location | Description | Expected Outcome |")
        lines.append("|---|---|---|---|")
        for case in cases:
            location = case.location or "—"
            lines.append(
                f"| `{case.id}` | `{location}` | {case.description} | "
                f"{case.expected_outcome} |"
            )
        lines.append("")

    lines.append("## Regenerating")
    lines.append("")
    lines.append(
        "```\npython prism_tools.py dataset build-hostile-demo "
        f"--output {result.project_root} --guide\n```"
    )
    lines.append("")
    lines.append(
        "Generation is deterministic for a fixed `--seed`, so regenerating "
        "with the same seed should reproduce byte-identical text/tabular "
        "output (binary formats such as `.xlsx` may still differ)."
    )
    return "\n".join(lines) + "\n"


def write_demo_guide(result: HostileGenerationResult, path: Path) -> Path:
    path = Path(path)
    path.write_text(render_demo_guide(result), encoding="utf-8")
    return path
